# Copyright (c) 2021 Nordic Semiconductor ASA
# SPDX-License-Identifier: Apache-2.0

manifest:
  self:
    west-commands: scripts/west-commands.yml

  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos

  group-filter: [+optional] #this addes canopennode

  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: v4.3.0
      # revision: v4.2.1
      # revision: v4.1.0
      # revision: main
      import:
        # By using name-allowlist we can clone only the modules that are
        # strictly needed by the application.
        name-allowlist:
          - canopennode
          - cmsis      # required by the ARM port
          - cmsis_6    # required by the ARM port for Cortex-M
          - cmsis-dsp
          - hal_espressif
          - hal_infineon
          - hal_nordic # required by the custom_plank board (Nordic based)
          - hal_stm32  # required by the nucleo_f302r8 board (STM32 based)
          - hal_ti
          - liblc3
          - libmetal
          - littlefs
          - lvgl
          - mbedtls
          - mcuboot
          - net-tools
          - open-amp
          - segger
          - tinycrypt
          - zcbor
